CREATE TABLE "account" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner" varchar NOT NULL,
  "balance" INT NOT NULL,
  "currency" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "entries" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" INT NOT NULL,
  "amount" INT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE TABLE "transfer" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "from_account_id" INT NOT NULL,
  "to_account_id" INT NOT NULL,
  "amount" INT NOT NULL,
  "created_at" TIMESTAMPTZ DEFAULT (now())
);


CREATE INDEX ON "account" ("owner");

CREATE INDEX ON "entries" ("account_id");

CREATE INDEX ON "transfer" ("from_account_id");

CREATE INDEX ON "transfer" ("to_account_id");

CREATE INDEX ON "transfer" ("from_account_id", "to_account_id");

ALTER TABLE "entries" ADD FOREIGN KEY ("account_id") REFERENCES "account" ("id");

ALTER TABLE "transfer" ADD FOREIGN KEY ("from_account_id") REFERENCES "account" ("id");

ALTER TABLE "transfer" ADD FOREIGN KEY ("to_account_id") REFERENCES "account" ("id");
