definitions:
  api.createUserRequest:
    properties:
      email:
        type: string
      full_name:
        type: string
      hashed_password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - email
    - full_name
    - hashed_password
    - username
    type: object
  api.loginUserRequest:
    properties:
      hashed_password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - hashed_password
    - username
    type: object
info:
  contact: {}
paths:
  /user:
    post:
      consumes:
      - application/json
      description: Creates a new user with the provided details
      parameters:
      - description: User creation request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.createUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create a new user
      tags:
      - Users
  /user/login:
    post:
      consumes:
      - application/json
      description: Logins a user with the provided details
      parameters:
      - description: Login User creation request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.loginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Login created user
      tags:
      - Users
swagger: "2.0"
